create table if not exists public.waitlist_entries (
  id bigint generated by default as identity primary key,
  client_id text not null unique,
  email text not null,
  role text not null,
  scenario text not null,
  message text,
  queue_position integer,
  source text,
  page_url text,
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.waitlist_entries enable row level security;

grant usage on schema public to anon;
grant insert (
  client_id,
  email,
  role,
  scenario,
  message,
  queue_position,
  source,
  page_url,
  user_agent
) on table public.waitlist_entries to anon;
grant usage on sequence public.waitlist_entries_id_seq to anon;

drop policy if exists "Allow anonymous waitlist inserts" on public.waitlist_entries;

create policy "Allow anonymous waitlist inserts"
on public.waitlist_entries
for insert
to anon
with check (
  char_length(client_id) between 16 and 80
  and email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'
  and char_length(email) <= 320
  and char_length(role) between 1 and 80
  and char_length(scenario) between 1 and 120
  and char_length(coalesce(message, '')) <= 2000
  and queue_position between 1 and 999999
  and char_length(coalesce(source, '')) <= 120
  and char_length(coalesce(page_url, '')) <= 500
  and char_length(coalesce(user_agent, '')) <= 500
);
